### ISSUE TITLE
Fixing and adjusting MimeTypes for Network Abstraction Layer

### ISSUE THREAD

**Issue by bmenne-dspace** [modelica/fmi-ls-bus#170]
Currently the MimeTypes for the Network Abstraction are already specified in version 1.0.0. However, the alpha/beta status should also be expressed here in order to rule out problems in identifying the version if there is an API change between alpha, beta and final version.

![image](https://github.com/modelica/fmi-ls-bus/assets/18484379/fb4df3af-e22d-4ae4-a5a7-0cb5d867e9a9)

**Comment by chrbertsch** [comment]
FMI Design Webmeeting: 

Benedikt: we could put the version information in the manifest.
Pierre: You could use MIME-Type (optional) arguments. We use this in the OSI Standard. You do not have to dispatch on the MIME-Type ... let the version handling do the work. Coding the version in the MIME-type is not so good ...
Benedikt: I like the option; example: application/vnd.isac.fcs; version="1.0-3.1"
Pierre: does not have to be in double quotes ... perhaps it is due to the "-".
Benedikt: Would we include "alpha, beta ..."?
Pierre: yes, I would do so.

@bmenne-dspace : i will create a PR
