### ISSUE TITLE
Fix github build infrastructure (again)

### ISSUE THREAD

**Issue by andreas-junghanns** [modelica/fmi-ls-bus#4]
I messed up what @pmai added to the repo.
Can either @pmai or @t-sommer fix this again on top of the current version, please?

**Comment by pmai** [comment]
I don't know what exactly you mean, but I have fixed the image references (no need to include the images part, since that is the image directory), and I have reverted the CRLF-duplicate of my initial README commit that should have been rebased out of the PR prior to merging. Does this work for you now? 

BTW the architecture image seems to have a duplicate of the Bus Simulator FMU and not the bus simulation by importer picture in it?

**Comment by andreas-junghanns** [comment]
> I don't know what exactly you mean, but I have fixed the image references (no need to include the images part, since that is the image directory), and I have reverted the CRLF-duplicate of my initial README commit that should have been rebased out of the PR prior to merging. Does this work for you now?

Yes, perfect - thank you!

> BTW the architecture image seems to have a duplicate of the Bus Simulator FMU and not the bus simulation by importer picture in it?

Yes, I noticed and asked @PTaeuberDS to have a look.
